import ForgotPassword from "../pages/Fogotpassword/Forgotpassword"

export const text={
    myApp:'My App',
    courseManagement:'Courses Management',
    Loading:'Loading content......',
    institute:'Institute',
    courseName:'Course Name',
    price:'Price: ',
    charges:'Charges',
    editCourse:'Edit Course',
    totalCourses:'Total Courses: ',
    confirmDelete:'Confirm Deletion',
    loadingDashboard:'Loading Dashboard.....',
    dashboardOverview:'Dashboard Overview',
    totalTeachers:'Total Teachers',
    totalStudents:'Total Students',
    active:'Active',
    inactive:'Inactive',
    logout:'Logout',
    average:'Avg Students/Course',
    courseEnrollment:'Course Enrollment Distribution',
    recentTeachers:'Recent Teachers',
    recentStudents:'Recent Students',
    addNewStudent:'Add New Student',
    selectedCourse: 'Selected Course',
    editstudent: 'Edit Student',
    editTeacher: 'Edit Teacher',
    name:'Name',
    grade:'Grade',
    courses:'Course',
    department:'Department',
    status:'Status',
    Actions:'Actions',
    availableCourses:'Available Courses(Select up to 3)',
    error:'Error',
    addNewTeacher:'Add new teacher',
    email:'Email',
    teacher:'Teachers',
    addTeacher:'+Add Teacher',
    noTeacher:'No teachers available',
    newPassword:'New Password',
    confirmPassword:'Confirm New Password',
    login: 'Login',
    signup: 'SignUp',
    password:'Password',
    firstName:'First Name',
    lastName:'Last Name',
    confirmPass:'Confirm Password',
}

export const buttonText={
    addCourse:'Add',
    edit:'Edit',
    delete:'Delete',
    cancel:'Cancel',
    save:'Save',
    remove:'Remove',
    logout:'Logout',
    verifyEmail:'Verify Email',
    backToLogin:'Back To Login',
    resetPassord:'Reset Password',
    forgotPassword:'Forgot Password?',
    signup:'Sign Up',
    login:'Login',

}
export const messageText={
 noCourses: 'No courses assigned',
 courseDeleted:'Course deleted successfully',
 courseAdded:'Course added successfully',
 courseUpdated:'Course updated successfully',
 teacherDeleted:'Teacher deleted successfully',
 teacherAdded:'Teacher added successfully',
 teacherUpdated:'Teacher updated successfully',
 confirmationDelete:'Are you sure you want to delete',
 dontHaveAcc:'Don\'t have an account?',
 haveAcc:'Already have an account?',
}